// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recruit_Form.Data;

#nullable disable

namespace Recruit_Form.Migrations
{
    [DbContext(typeof(DbContextApp1))]
    partial class DbContextApp1ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Recruit_Form.Model.PersonalInformation", b =>
                {
                    b.Property<int>("PersonalInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalInformationId"));

                    b.Property<int>("Appearance")
                        .HasColumnType("int");

                    b.Property<string>("BirthYaer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommunityCovenant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComputerSkills")
                        .HasColumnType("int");

                    b.Property<int>("Conservation")
                        .HasColumnType("int");

                    b.Property<int>("DegreeOfConfrontation")
                        .HasColumnType("int");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fourth_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentifieWorkPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFamiliesMartyrsAndWounded")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedAddition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificSpecialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sessions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkilledInDriving")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkplacesExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("doctrinal_Information")
                        .HasColumnType("int");

                    b.Property<int>("technical_Information")
                        .HasColumnType("int");

                    b.HasKey("PersonalInformationId");

                    b.ToTable("PerInform");
                });
#pragma warning restore 612, 618
        }
    }
}
